[package]
edition = "2021"
name = "walker"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.7.0", default-features = false, features = ["napi4"] }
napi-derive = "2.7.0"
may = "0.3"
may_minihttp = { git = "https://github.com/Xudong-Huang/may_minihttp.git" }
matchit = "0.6"
once_cell = { version = "1.14.0", features = ["parking_lot"] }
usync = "0.2"
oneshot = "*"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
