[package]
edition = "2021"
name = "walker"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.7.0", default-features = false, features = ["napi4", "serde-json"] }
napi-derive = "2.7.0"
may = "0.3"
may_minihttp = { git = "https://github.com/JackThomson2/may_minihttp.git" }
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git" }
matchit = "0.6"
usync = "0.2"
snmalloc-rs = { version = "*", features = ["build_cc"] }
bytes = "1.2.1"
serde_json = "1.0.85"
lazy_static = "1.4.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"
