[package]
edition = "2021"
name = "walker"
version = "0.0.0"

[dependencies]
matchit = "0.6"
snmalloc-rs = { version = "*", features = ["build_cc"] }
bytes = "1.2.1"
serde_json = "1.0.85"
itoa = "1.0.3"
tokio = { version = "1", features = [
  "full",
  "fs",
  "io-util",
  "io-std",
  "macros",
  "net",
  "parking_lot",
  "process",
  "rt",
  "signal",
  "sync",
  "time"
] }
v8 = "0.51.0"
hyper = { version = "0.14.20", features = [
    "http1",
    "http2",
    "server",
    "tcp"
] }
async-scoped = "0.7.0"
flume = "0.10.14"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"
incremental = false
