[package]
edition = "2021"
name = "walker"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.7.0", default-features = false, features = ["napi4", "serde-json"] }
napi-derive = "2.7.0"
may = "0.3"
may_minihttp = { path = "../may_minihttp" }
matchit = "0.6"
once_cell = { version = "1.14.0", features = ["parking_lot"] }
usync = "0.2"
mimalloc = { version = "*", default-features = false }
bytes = "1.2.1"
yarte = { version = "0.15", features = ["bytes-buf", "json"] }
serde_json = "1.0.85"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
