/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function newRoute(route: string, callback: (...args: any[]) => any): void
export function start(address: string): void
export class RequestBlob {
  getMessage(): string
  setResponse(response: string): void
}
